#!/bin/sh
set -eu
MARKDOWN=smu
IFS='	'

# Create tab separated file with filename, title, creation date, last update
index_tsv() {
	for f in "$1"/*.md
	do
		title=$(gsed -n '/^# /{s/# //p; q}' "$f")
		printf '%s\t%s\t%s\t%s\n' "$f" "${title:="No Title"}"
	done
}

index_html() {
	# Print header
	title=$(gsed -n '/^# /{s/# //p; q}' index.md)
	gsed "s/{{TITLE}}/$title/" header.html

	# Intro text
	$MARKDOWN index.md

	echo "<ul>"

	# Posts
	while read -r f title created; do
		link=$(echo "$f" | gsed -E 's|.*/(.*).md|\1/|')
		created=$(echo $(head -3 "$f" | tail -1))
	 	echo "<li>$created <br> <a href=\"$link\">$title</a></li><br>"
	done < "$1" | sort -r

	echo "</ul>"

	# Print footer after post list
	cat footer.html
}

atom_xml() {
	uri=$(gsed -rn '/atom.xml/ s/.*href="([^"]*)".*/\1/ p' header.html)
	domain=$(echo "$uri" | gsed 's/atom.xml//g' | gsed 's|/[^/]*$||')

	cat <<EOF
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
	<title>$(gsed -n '/^# /{s/# //p; q}' index.md)</title>
	<link href="$domain/atom.xml" rel="self" />
	<updated>$(date +%FT%TZ)</updated>
	<author>
		<name>$(git config user.name)</name>
	</author>
	<id>$domain,$(date +%F):default-atom-feed/</id>
EOF

	while read -r f title created; do

		content=$($MARKDOWN "$f" | gsed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g;
s/"/\&quot;/g; s/'"'"'/\&#39;/g')
		post_link=$(echo "$f" | gsed -E 's|posts/(.*).md|\1|')
		basic_date=$(echo $(head -3 "$f" | tail -1))
		published_date=$(gdate -d $basic_date -u +%Y-%m-%dT10:%M:%SZ)

		cat <<EOF
	<entry>
		<title>$title</title>
		<content type="html">$content</content>
		<link href="$domain/$post_link"/>
		<id>$domain/$post_link</id>
		<updated>$published_date</updated>
		<published>$published_date</published>
	</entry>
EOF
	done < "$1"

	echo '</feed>'
}

write_page() {
	filename=$1
	directory=$(echo $(basename "$filename" .md))
	$(mkdir -p build/$directory)
	target=$(echo "$filename" | gsed -r 's|\w+/(.*).md|build/\1/index.html|')
	created=$(echo $(head -3 "$filename" | tail -1))
	title=$2

	$MARKDOWN "$filename" | \
		cat header.html - |\
		gsed "s|{{TITLE}}|$title|" \
		> "$target" && cat footer.html >> "$target"
}

rm -rf build && mkdir build

# Blog posts
index_tsv posts | sort -rt "	" -k 3 > build/posts.tsv
index_html build/posts.tsv > build/index.html
atom_xml build/posts.tsv > build/atom.xml
while read -r f title created; do
	write_page "$f" "$title" "$created"
done < build/posts.tsv

# Pages
index_tsv pages > build/pages.tsv
while read -r f title created; do
	write_page "$f" "$title" "$created"
done < build/pages.tsv
